feat: added products listing page
kedark152/AgroStores pull request #3
Opened 2022-02-13 13:26 UTC by kedark152

#feat: added product listing page with filters section
1.	Product listing page with 6 agro products, will add more products in future.
2.	added filters section on left sidebar.

2022-02-13 13:38 UTC, Hamdrive requested changes
Good work done, great use of inline comments
Suggest to look into the fix for range input

2022-02-13 13:38 UTC, Hamdrive commented on pages/products.html
> +    />
Consider importing this into a main CSS file, thus it will always be implicitly imported instead of mentioning it in `head` section

2022-02-13 13:38 UTC, Hamdrive commented on pages/products.html
> +          value="3"
Instead you can use `step` attribute to give breakpoints in your slider

2022-02-13 13:45 UTC, Roshannair24 commented
Nice theme, looks good to merge

2022-02-13 13:45 UTC, Roshannair24 approved these changes

2022-02-14 10:17 UTC, kedark152 commented on pages/products.html
> +    />
Thanks Hamza, I have made suggested changes. Please check and approve them.

2022-02-14 10:17 UTC, kedark152 commented on pages/products.html
> +          value="3"
Thanks Hamza, I have made suggested changes. Please check and approve them.

2022-02-14 12:08 UTC, Hamdrive approved these changes
Looks good, changes requested have been implemented
Ready to merge!

2022-02-14 16:59 UTC, merged